### ISSUE TITLE
Current Version not Working

### ISSUE THREAD

**Issue by silentgecko** [KamuiMaster/bdo-guild-quest-mod#1]
Atm the current version is v239 i think, the game crashes when you want to start the game with your tool

**Comment by KingPin** [comment]
fixed as of this mornings commit.

**Comment by KamuiMaster** [comment]
if it happen again, just bump me here again, gg.

**Comment by konn181** [comment]
@KamuiMaster today's patch broke it again FYI

**Comment by FriedNoobles** [comment]
Bumparoo, does anyone have any other contact details for KamuiMaster? lol

**Comment by silentgecko** [comment]
@KamuiMaster maybe you could tell me how to change it by myself, than i could support you on this ;)

**Comment by Maclav1** [comment]
I used quickBMS on the paz files, but couldn't find the stringtables. They might be in the meta file which I don't have the qbms script for. :(

**Comment by Maclav1** [comment]
@KamuiMaster Id be happy to do updates if you show me the tool/quickbms script you're using to get the string tables out.

**Comment by FriedNoobles** [comment]
might need to open a new issue? not sure if he gets alerts with this one, or if hes even updating it anymore?!

**Comment by KingPin** [comment]
maybe hes just busy for the weekend. but yeah I wouldn't mind doing pull requests if there was some way to replicate kamui's work.

**Comment by konn181** [comment]
@KamuiMaster any update? are you waiting for the patch Wednesday till next version release?

**Comment by Gracen-TT** [comment]
If you look around I believe he has his discord username on github somewhere

**Comment by Grelot11** [comment]
Still need updating..

**Comment by KingPin** [comment]
todays patch (2016-11-02) did **NOT** break it.

**Comment by silentgecko** [comment]
v275 now and it doesn't work anymore (atleast i tried it...)

**Comment by silentgecko** [comment]
thanks for the fix!

**Comment by silentgecko** [comment]
and again broken ;)

**Comment by grepString** [comment]
Bumping this issue. Current version is outdated

**Comment by AMGarkin** [comment]
@grepString If you are ok just with english translation, you can try this [file](https://www.dropbox.com/s/8h65mgyl1bi4pgu/languagedata_en_v337.zip?dl=0).

**Comment by grepString** [comment]
@AMGarkin Thanks, that worked perfectly.

**Comment by SlyKyti** [comment]
Is there anything I can do to update the BDO guild quest previewer? Please?

**Comment by AMGarkin** [comment]
[Updated english language data for v340](https://www.dropbox.com/s/6ri6wuugomzo2uy/prestringtable_en_v340.zip?dl=0).

**Comment by comoriano76** [comment]
@AMGarkin TY ;)
Can you do it for french version ? ^_^

**Comment by AMGarkin** [comment]
@comoriano76 [prestringtable_fr_v340.zip](https://www.dropbox.com/s/w3g6rtkfemvmbxh/prestringtable_fr_v340.zip?dl=0)
There are a few issues with french version:
- I don't speak french, so there will be some wrongly translated texts.
- "[Trade] Vitalizing Local Economy" quests are not translated to french even in original language files, so I'll leave it in english.
- "[Événement] Aventurier de Margoria" ID 273 says "Pêcher un Espadon". French "Espadon" refers to two different fishes 새치 (Swordfish) and 황새치 (Yellow Swordfis). For this quest you'll need the second one.
- I didn't test it at all.

**Comment by comoriano76** [comment]
thanks @AMGarkin it's working :)

**Comment by SlyKyti** [comment]
Garkin I loved you in ESO and here you are again to save the day. Kudos and
thanks
