### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by FriedNoobles** [KamuiMaster/bdo-guild-quest-mod#6]
This mod currently isnt working, though not much point updating til after maintenence tomorrow, if your still working on this.

Thanks for this mod though, it has really helped :)

**Comment by KingHawkk** [comment]
It has been working for that past 2 weeks and currently it's working too...

**Comment by FriedNoobles** [comment]
Gives me a crash to desktop O.o

**Comment by FriedNoobles** [comment]
is broked now

**Comment by AMGarkin** [comment]
@FriedNoobles You'll have to wait for the next update, current version doesn't work with the latest game patch (v320). As I didn't want to wait, I have modified english translation myself ([here](https://www.dropbox.com/s/osjsc188okqowqe/prestringtable_en_v320.zip?dl=0)).
